### ISSUE TITLE
Affichage trop gros

### ISSUE THREAD

**Issue by arnaudlevy** [noesya/un-dictionnaireduclimat#1]
<img width="1657" alt="image" src="https://user-images.githubusercontent.com/2088968/225263551-617dd75e-a049-47c7-89d2-a72a610ee787.png">

Windows 10 pro version 22H2
Chrome 111
Résolution 1920x1080 ???

**Comment by arnaudlevy** [comment]
Sur la même config, le site de l'IUT est impeccable

**Comment by arnaudlevy** [comment]
[screencapture-dico-unric-org-fr-2023-03-15-10_21_02.pdf](https://github.com/noesya/un-dictionnaireduclimat/files/10978056/screencapture-dico-unric-org-fr-2023-03-15-10_21_02.pdf)

Il semble y avoir un pb avec plausible en console (bloqué ?)

**Comment by arnaudlevy** [comment]
Idem Brave et FF

**Comment by alexisben** [comment]
Pas de préférence de zoom ? (si je me mets à 110% ça chasse également, c'est plutôt normal)

**Comment by arnaudlevy** [comment]
a priori non

**Comment by arnaudlevy** [comment]
si c'est le zoom !!! bravo !
